export {
  type Clause,
  type AggregateOperator,
  type AggregateQuerySpec,
  type ArithmeticOp,
  type BinaryArithmeticExpression,
  type CmpOp,
  type Comparison,
  type Goal,
  type Literal,
  type Negation,
  type QuerySpec,
  type RelationalQuerySpec,
  type ScalarExpression,
  type Term,
  type UnaryArithmeticExpression,
  type UnaryArithmeticOp,
  MAX_ARITHMETIC_EXPRESSION_DEPTH,
  MAX_ARITHMETIC_EXPRESSION_NODES,
  canonicalKey,
  isArithmeticExpression,
  isComparison,
  isNegation,
  predKey,
  serializeClause,
  serializeGoal,
  serializeQuerySpec,
  serializeScalarExpression,
  serializeTerm,
} from './ast.js';
export {
  type AbsenceProof,
  type AggregateContribution,
  type AggregateProof,
  type Bindings,
  type DerivationProof,
  type ExplainedBindings,
  type ExplainedQueryBindings,
  type EvaluateOptions,
  type MaterializedFactWithProof,
  type ProofStep,
  type QueryProof,
  EngineLimitError,
  EngineSafetyError,
  evaluate,
  evaluateQuerySpec,
  evaluateQuerySpecWithProof,
  evaluateWithProof,
  literalMatches,
  materializeWithProof,
} from './evaluate.js';
export { ParseError } from './lexer.js';
export { parseProgram, parseQuery, parseQuerySpec } from './parser.js';
export {
  StratificationError,
  stratifyProgram,
  type StratifiedProgram,
  type StratifiedRule,
} from './stratify.js';
