export * from './engine/index.js';
export {
  MemoryStore,
  defaultRoot,
  type AssertResult,
  type MemorySource,
  type TemporalMemorySource,
  type MutationContext,
  type IdempotentMutationOperation,
  type ValidTimeMode,
  type SupersedeResult,
  type MemoryHistoryAction,
  type MemoryHistoryEvent,
  type MemoryHistory,
  type MemoryHistoryOptions,
  type RecordedSnapshotMetadata,
  type RecordedKnowledgeSnapshot,
  type JournalCheckpointNamespace,
  type JournalCheckpointArtifact,
  type JournalCompactionOptions,
  type JournalCompactionResult,
  MAX_HISTORY_EVENTS,
  MAX_OPERATION_ID_BYTES,
  MAX_JOURNAL_SEGMENTS,
  MAX_TOTAL_JOURNAL_ENTRIES,
  MAX_CHECKPOINT_BYTES,
  MAX_SUPERSEDE_PATTERNS,
  OperationConflictError,
  IncompleteHistoryError,
  type AutoCaptureBatch,
  type AutoCaptureFact,
  type AutoCaptureReview,
  type AutoCaptureReviewOptions,
  type AutoCaptureReservation,
  type AutoCaptureReservationRequest,
  type AutoCaptureStatus,
  type PruneAutoCaptureOptions,
} from './store/store.js';
export {
  DatalogDatabase,
  buildSqliteExtension,
  openDatalogDatabase,
  resolveSqliteExtensionPath,
  sqliteDatalogExecutionMode,
  type DatalogRow,
  type DatalogExplanation,
  type DatalogProof,
  type OpenDatalogDatabaseOptions,
  type SqliteDatalogExecutionMode,
} from './sqlite/extension.js';
export {
  type ChatMessage,
  type LlmClient,
  type LlmConfig,
  DEFAULT_MODEL,
  OpenRouterClient,
  clientFromEnv,
  lazyClientFromEnv,
} from './llm/client.js';
export {
  type PipelineDeps,
  type RecallOptions,
  type RecallPruningReport,
  type RecallQueryReview,
  type RecallQueryReviewReason,
  type RecallResult,
  type RecallSchemaAttempt,
  type RecallSchemaAttemptOutcome,
  type RecallStatus,
  type RememberResult,
  type RememberOptions,
  type RememberTranscriptOptions,
  type RetrievalResult,
  recallQuestion,
  rememberTranscriptText,
  rememberText,
  retrieveQuestion,
} from './llm/pipeline.js';
export {
  type QueryPromptVariant,
  transcriptExtractionSystemPrompt,
} from './llm/prompts.js';
export {
  DEFAULT_RECALL_SCHEMA_BYTES,
  DEFAULT_RECALL_SCHEMA_PREDICATES,
  MAX_RECALL_SCHEMA_BYTES,
  MAX_RECALL_SCHEMA_CANDIDATES,
  MAX_RECALL_SCHEMA_CLAUSES,
  MAX_RECALL_SCHEMA_PREDICATES,
  MAX_RECALL_QUESTION_WORDS,
  RecallSchemaBudgetError,
  type RecallSchemaDiagnostics,
  type RecallSchemaOptions,
  type RecallSchemaSelection,
  recallSchemaDiagnostics,
  selectRecallSchema,
} from './llm/schema.js';
export {
  autoCaptureClaudeStop,
  type AutoCaptureDeps,
  type AutoCaptureOptions,
  type AutoCaptureResult,
} from './autocapture/capture.js';
export {
  DEFAULT_AUTO_CAPTURE_DAILY_CAP,
  MANAGED_HOOK_MARKER,
  MAX_AUTO_CAPTURE_DAILY_CAP,
  defaultClaudeSettingsPath,
  installClaudeHook,
  removeClaudeHook,
  validateAutoCaptureDailyCap,
  validateAutoCaptureTailBytes,
  type HookChangeResult,
  type InstallClaudeHookOptions,
  type RemoveClaudeHookOptions,
} from './autocapture/hooks.js';
export {
  DEFAULT_TRANSCRIPT_TAIL_BYTES,
  MAX_TRANSCRIPT_TAIL_BYTES,
  defaultClaudeConfigDir,
  parseClaudeStopHookInput,
  readClaudeTranscriptTail,
  type ClaudeStopHookInput,
  type ClaudeTranscriptTail,
  type TranscriptReadOptions,
} from './autocapture/transcript.js';
export { createServer, serveStdio } from './mcp/server.js';
export {
  type AbsenceGraphNode,
  type AggregateGraphNode,
  buildExplanationGraph,
  explainKnowledge,
  type ClaimGraphNode,
  type ConflictGraphNode,
  type EntityGraphNode,
  type ExplainKnowledgeOptions,
  type ExplainKnowledgeResult,
  type ExplainedKnowledgeRow,
  type ExplanationGraph,
  type ExplanationGraphEdge,
  type ExplanationGraphNode,
  type ExplanationRule,
  type ProofGraphNode,
  type ResultGraphNode,
  type SourcedDerivationProof,
  type SourcedAbsenceProof,
  type SourcedAggregateProof,
  type SourcedProofStep,
  type SourcedQueryProof,
} from './knowledge/graph.js';
export {
  inspectConflicts,
  MAX_CONFLICT_FOCUS_BYTES,
  type ConflictCluster,
  type ConflictConstraint,
  type ConflictViolation,
  type ConflictViewOptions,
  type ConflictViewResult,
} from './knowledge/conflicts.js';
export {
  TENTATIVE_PREDICATE,
  MAX_TENTATIVE_FACTS,
  MAX_TENTATIVE_CLAUSE_BYTES,
  TrustMetadataError,
  assertTrustMetadataSafety,
  decodeTentativeDeclaration,
  isTentativeDeclaration,
  isTrustMetadataPredicate,
  listTentativeClaims,
  projectTrustKnowledge,
  tentativeClaimId,
  wrapTentativeFacts,
  type KnowledgeTrust,
  type TentativeClaim,
  type TentativeResolutionAction,
  type TrustKnowledgeView,
  type TrustProjection,
  type TrustViewMode,
} from './knowledge/trust.js';
export {
  MAX_TENTATIVE_REVIEW_CLAIMS,
  assertTentativeFacts,
  resolveTentativeFacts,
  reviewTentativeClaims,
  type StoredTentativeClaim,
  type TentativeAssertionResult,
  type TentativeResolutionResult,
} from './knowledge/trust-store.js';
export {
  MAX_GRAPH_NEIGHBOR_DEPTH,
  MAX_GRAPH_NODE_ID_BYTES,
  MAX_GRAPH_RESULT_ROW,
  selectExplanationGraph,
  selectKnowledgeGraph,
  type ExplanationGraphSelection,
  type ExplanationGraphSelector,
  type GraphSelectableExplanation,
} from './knowledge/graph-navigation.js';
export {
  ENTITY_ALIAS_PREDICATE,
  ENTITY_POSITION_PREDICATE,
  MAX_ENTITY_ALIASES,
  MAX_ENTITY_POSITIONS,
  EntityIdentityError,
  EntityResolver,
  buildEntityResolver,
  canonicalizeKnowledge,
  isEntityMetadataDeclaration,
  isEntityMetadataPredicate,
  literalKnowledge,
  type CanonicalKnowledgeView,
  type EntityAlias,
  type EntityIdentityMode,
  type EntityPosition,
  type EntityProjection,
  type EntityRewrite,
} from './knowledge/identity.js';
export {
  checkIntegrity,
  DEFAULT_MAX_INTEGRITY_VIOLATIONS,
  MAX_INTEGRITY_CONSTRAINTS,
  MAX_INTEGRITY_VIOLATIONS,
  type IntegrityCheckOptions,
  type IntegrityCheckResult,
  type IntegrityConstraintCheck,
  type IntegrityStatus,
} from './knowledge/integrity.js';
export {
  enforceIntegrityCandidate,
  IntegrityViolationError,
  type IntegrityEnforcementMode,
  type IntegrityEnforcementOptions,
  type IntegrityViolationRef,
} from './knowledge/enforcement.js';
